# fly.toml app configuration file generated for shannon-blog-backend on 2023-09-11T18:40:02-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shannon-blog-backend"
primary_region = "atl"

[build]

[http_service]
  internal_port = 3005
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
